### ISSUE TITLE
[BUG] Build errors after updating to 2.8.1

### ISSUE THREAD

**Issue by Cyberuben** [dynamoose/dynamoose#1253]
### Summary:

Dynamoose won't build anymore after updating to the latest version (2.8.1)

#### Schema
Irrelevant

#### Model
Irrelevant

#### General
```
$ tsc --build tsconfig.json
node_modules/dynamoose/dist/DocumentRetriever.d.ts:32:28 - error TS1110: Type expected.

32         sort?: SortOrder | `${SortOrder}`;
                              ~~~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:33:5 - error TS1128: Declaration or statement expected.

33     };
       ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:34:58 - error TS1005: '(' expected.

34     getRequest: (this: DocumentRetriever) => Promise<any>;
                                                            ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:42:14 - error TS1005: ',' expected.

42     exec(this: DocumentRetriever, callback?: any): any;
                ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:42:44 - error TS1109: Expression expected.

42     exec(this: DocumentRetriever, callback?: any): any;
                                              ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:42:50 - error TS1005: ';' expected.

42     exec(this: DocumentRetriever, callback?: any): any;
                                                    ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:22 - error TS1005: ',' expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                        ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:39 - error TS1109: Expression expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                                         ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:56 - error TS1005: ',' expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                                                          ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:99 - error TS1109: Expression expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                                                                                                     ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:44:1 - error TS1128: Declaration or statement expected.

44 }
   ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:29 - error TS1110: Type expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                               ~~~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:43 - error TS1005: ';' expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                                             ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:44 - error TS1128: Declaration or statement expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                                              ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:54 - error TS1005: '(' expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                                                        ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:71:22 - error TS1005: ',' expected.

71     constructor(model: Model<Document>, object?: ConditionInitalizer);
                        ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:71:39 - error TS1109: Expression expected.

71     constructor(model: Model<Document>, object?: ConditionInitalizer);
                                         ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:71:48 - error TS1109: Expression expected.

71     constructor(model: Model<Document>, object?: ConditionInitalizer);
                                                  ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:72:1 - error TS1128: Declaration or statement expected.

72 }
   ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:32:28 - error TS1110: Type expected.

32         sort?: SortOrder | `${SortOrder}`;
                              ~~~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:33:5 - error TS1128: Declaration or statement expected.

33     };
       ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:34:58 - error TS1005: '(' expected.

34     getRequest: (this: DocumentRetriever) => Promise<any>;
                                                            ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:42:14 - error TS1005: ',' expected.

42     exec(this: DocumentRetriever, callback?: any): any;
                ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:42:44 - error TS1109: Expression expected.

42     exec(this: DocumentRetriever, callback?: any): any;
                                              ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:42:50 - error TS1005: ';' expected.

42     exec(this: DocumentRetriever, callback?: any): any;
                                                    ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:22 - error TS1005: ',' expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                        ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:39 - error TS1109: Expression expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                                         ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:56 - error TS1005: ',' expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                                                          ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:99 - error TS1109: Expression expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                                                                                                     ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:44:1 - error TS1128: Declaration or statement expected.

44 }
   ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:29 - error TS1110: Type expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                               ~~~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:43 - error TS1005: ';' expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                                             ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:44 - error TS1128: Declaration or statement expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                                              ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:54 - error TS1005: '(' expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                                                        ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:71:22 - error TS1005: ',' expected.

71     constructor(model: Model<Document>, object?: ConditionInitalizer);
                        ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:71:39 - error TS1109: Expression expected.

71     constructor(model: Model<Document>, object?: ConditionInitalizer);
                                         ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:71:48 - error TS1109: Expression expected.

71     constructor(model: Model<Document>, object?: ConditionInitalizer);
                                                  ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:72:1 - error TS1128: Declaration or statement expected.

72 }
   ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:32:28 - error TS1110: Type expected.

32         sort?: SortOrder | `${SortOrder}`;
                              ~~~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:33:5 - error TS1128: Declaration or statement expected.

33     };
       ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:34:58 - error TS1005: '(' expected.

34     getRequest: (this: DocumentRetriever) => Promise<any>;
                                                            ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:42:14 - error TS1005: ',' expected.

42     exec(this: DocumentRetriever, callback?: any): any;
                ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:42:44 - error TS1109: Expression expected.

42     exec(this: DocumentRetriever, callback?: any): any;
                                              ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:42:50 - error TS1005: ';' expected.

42     exec(this: DocumentRetriever, callback?: any): any;
                                                    ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:22 - error TS1005: ',' expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                        ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:39 - error TS1109: Expression expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                                         ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:56 - error TS1005: ',' expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                                                          ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:99 - error TS1109: Expression expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                                                                                                     ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:44:1 - error TS1128: Declaration or statement expected.

44 }
   ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:29 - error TS1110: Type expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                               ~~~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:43 - error TS1005: ';' expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                                             ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:44 - error TS1128: Declaration or statement expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                                              ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:54 - error TS1005: '(' expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                                                        ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:71:22 - error TS1005: ',' expected.

71     constructor(model: Model<Document>, object?: ConditionInitalizer);
                        ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:71:39 - error TS1109: Expression expected.

71     constructor(model: Model<Document>, object?: ConditionInitalizer);
                                         ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:71:48 - error TS1109: Expression expected.

71     constructor(model: Model<Document>, object?: ConditionInitalizer);
                                                  ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:72:1 - error TS1128: Declaration or statement expected.

72 }
   ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:32:28 - error TS1110: Type expected.

32         sort?: SortOrder | `${SortOrder}`;
                              ~~~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:33:5 - error TS1128: Declaration or statement expected.

33     };
       ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:34:58 - error TS1005: '(' expected.

34     getRequest: (this: DocumentRetriever) => Promise<any>;
                                                            ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:42:14 - error TS1005: ',' expected.

42     exec(this: DocumentRetriever, callback?: any): any;
                ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:42:44 - error TS1109: Expression expected.

42     exec(this: DocumentRetriever, callback?: any): any;
                                              ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:42:50 - error TS1005: ';' expected.

42     exec(this: DocumentRetriever, callback?: any): any;
                                                    ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:22 - error TS1005: ',' expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                        ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:39 - error TS1109: Expression expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                                         ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:56 - error TS1005: ',' expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                                                          ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:99 - error TS1109: Expression expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                                                                                                     ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:44:1 - error TS1128: Declaration or statement expected.

44 }
   ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:29 - error TS1110: Type expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                               ~~~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:43 - error TS1005: ';' expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                                             ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:44 - error TS1128: Declaration or statement expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                                              ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:54 - error TS1005: '(' expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                                                        ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:71:22 - error TS1005: ',' expected.

71     constructor(model: Model<Document>, object?: ConditionInitalizer);
                        ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:71:39 - error TS1109: Expression expected.

71     constructor(model: Model<Document>, object?: ConditionInitalizer);
                                         ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:71:48 - error TS1109: Expression expected.

71     constructor(model: Model<Document>, object?: ConditionInitalizer);
                                                  ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:72:1 - error TS1128: Declaration or statement expected.

72 }
   ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:32:28 - error TS1110: Type expected.

32         sort?: SortOrder | `${SortOrder}`;
                              ~~~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:33:5 - error TS1128: Declaration or statement expected.

33     };
       ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:34:58 - error TS1005: '(' expected.

34     getRequest: (this: DocumentRetriever) => Promise<any>;
                                                            ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:42:14 - error TS1005: ',' expected.

42     exec(this: DocumentRetriever, callback?: any): any;
                ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:42:44 - error TS1109: Expression expected.

42     exec(this: DocumentRetriever, callback?: any): any;
                                              ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:42:50 - error TS1005: ';' expected.

42     exec(this: DocumentRetriever, callback?: any): any;
                                                    ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:22 - error TS1005: ',' expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                        ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:39 - error TS1109: Expression expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                                         ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:56 - error TS1005: ',' expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                                                          ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:99 - error TS1109: Expression expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                                                                                                     ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:44:1 - error TS1128: Declaration or statement expected.

44 }
   ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:29 - error TS1110: Type expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                               ~~~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:43 - error TS1005: ';' expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                                             ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:44 - error TS1128: Declaration or statement expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                                              ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:54 - error TS1005: '(' expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                                                        ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:71:22 - error TS1005: ',' expected.

71     constructor(model: Model<Document>, object?: ConditionInitalizer);
                        ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:71:39 - error TS1109: Expression expected.

71     constructor(model: Model<Document>, object?: ConditionInitalizer);
                                         ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:71:48 - error TS1109: Expression expected.

71     constructor(model: Model<Document>, object?: ConditionInitalizer);
                                                  ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:72:1 - error TS1128: Declaration or statement expected.

72 }
   ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:32:28 - error TS1110: Type expected.

32         sort?: SortOrder | `${SortOrder}`;
                              ~~~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:33:5 - error TS1128: Declaration or statement expected.

33     };
       ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:34:58 - error TS1005: '(' expected.

34     getRequest: (this: DocumentRetriever) => Promise<any>;
                                                            ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:42:14 - error TS1005: ',' expected.

42     exec(this: DocumentRetriever, callback?: any): any;
                ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:42:44 - error TS1109: Expression expected.

42     exec(this: DocumentRetriever, callback?: any): any;
                                              ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:42:50 - error TS1005: ';' expected.

42     exec(this: DocumentRetriever, callback?: any): any;
                                                    ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:22 - error TS1005: ',' expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                        ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:39 - error TS1109: Expression expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                                         ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:56 - error TS1005: ',' expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                                                          ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:99 - error TS1109: Expression expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                                                                                                     ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:44:1 - error TS1128: Declaration or statement expected.

44 }
   ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:29 - error TS1110: Type expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                               ~~~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:43 - error TS1005: ';' expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                                             ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:44 - error TS1128: Declaration or statement expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                                              ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:54 - error TS1005: '(' expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                                                        ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:71:22 - error TS1005: ',' expected.

71     constructor(model: Model<Document>, object?: ConditionInitalizer);
                        ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:71:39 - error TS1109: Expression expected.

71     constructor(model: Model<Document>, object?: ConditionInitalizer);
                                         ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:71:48 - error TS1109: Expression expected.

71     constructor(model: Model<Document>, object?: ConditionInitalizer);
                                                  ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:72:1 - error TS1128: Declaration or statement expected.

72 }
   ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:32:28 - error TS1110: Type expected.

32         sort?: SortOrder | `${SortOrder}`;
                              ~~~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:33:5 - error TS1128: Declaration or statement expected.

33     };
       ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:34:58 - error TS1005: '(' expected.

34     getRequest: (this: DocumentRetriever) => Promise<any>;
                                                            ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:42:14 - error TS1005: ',' expected.

42     exec(this: DocumentRetriever, callback?: any): any;
                ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:42:44 - error TS1109: Expression expected.

42     exec(this: DocumentRetriever, callback?: any): any;
                                              ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:42:50 - error TS1005: ';' expected.

42     exec(this: DocumentRetriever, callback?: any): any;
                                                    ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:22 - error TS1005: ',' expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                        ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:39 - error TS1109: Expression expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                                         ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:56 - error TS1005: ',' expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                                                          ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:43:99 - error TS1109: Expression expected.

43     constructor(model: Model<Document>, typeInformation: DocumentRetrieverTypeInformation, object?: ConditionInitalizer);
                                                                                                     ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:44:1 - error TS1128: Declaration or statement expected.

44 }
   ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:29 - error TS1110: Type expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                               ~~~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:43 - error TS1005: ';' expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                                             ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:44 - error TS1128: Declaration or statement expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                                              ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:70:54 - error TS1005: '(' expected.

70     sort(order: SortOrder | `${SortOrder}`): Query<T>;
                                                        ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:71:22 - error TS1005: ',' expected.

71     constructor(model: Model<Document>, object?: ConditionInitalizer);
                        ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:71:39 - error TS1109: Expression expected.

71     constructor(model: Model<Document>, object?: ConditionInitalizer);
                                         ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:71:48 - error TS1109: Expression expected.

71     constructor(model: Model<Document>, object?: ConditionInitalizer);
                                                  ~

node_modules/dynamoose/dist/DocumentRetriever.d.ts:72:1 - error TS1128: Declaration or statement expected.

72 }
   ~
```

### Current output and behavior (including stack trace):

See build output above

### Expected output and behavior:

Dynamoose builds as intented

### Environment:

Operating System: macOS Big Sur
Operating System Version: 11.5.2
Node.js version (`node -v`): 15.10.0
NPM version: (`npm -v`): 7.5.3 (but using Yarn 1.22.10)
Dynamoose version: 2.8.1

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [x] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [x] I have tested the code provided and am confident it doesn't work as intended
- [x] I have filled out all fields above
- [x] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
@Cyberuben Update to the latest version of TypeScript.

**Comment by Cyberuben** [comment]
This seemed to be the issue indeed, multiple dependencies depended on TypeScript and an older version was used for building.
