### ISSUE TITLE
Query Condition Typings Incorrect [BUG]

### ISSUE THREAD

**Issue by benkburke** [dynamoose/dynamoose#927]
### Summary:
When using the Condition operators on the query() method, exec() is not found. This was previously working in versions prior to 2.2.1 (specifically 1.11.1 tested but others likely as well).

#### Schema
```
import * as dynamoose from "dynamoose";

const schema = new dynamoose.Schema({
  firstName: {
    type: String,
    required: true,
  },
  lastName: {
    type: String,
    required: true,
  },
  id: {
    type: String,
    default: "1234",
  },
});
```

#### Model
```
const model = dynamoose.model("Customers", schema, {
  create: false,
  update: false,
});
```

#### General
```
const queryOne = model.query("id").eq("1234").exec();
```

### Current output and behavior (including stack trace):

Property 'exec' does not exist on type 'Condition'.ts(2339)

### Expected output and behavior:

Method exec() should exist on type Condition and allow the query to be completed.

### Environment:

Operating System: Win 10
Operating System Version: Build 18362.836
Node.js version (`node -v`): 12.14.1
NPM version: (`npm -v`): 6.14.5
Dynamoose version: 2.2.1

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [x] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [x] I have tested the code provided and am confident it doesn't work as intended
- [x] I have filled out all fields above
- [x] I am running the latest version of Dynamoose

**Comment by hardyscc** [comment]
@benkburke This PR #925 should fix your problem, Do u mind to test and review it?
You can install that PR branch using:
```
npm install hardyscc/dynamoose --save
```

**Comment by benkburke** [comment]
@hardyscc 

Looks like there is an extra semi-colon in the package json script.  I receive the following error when trying to install the package:

1 verbose cli   'run',
1 verbose cli   'build:clean;',
1 verbose cli   'npm',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.14.1
4 verbose stack Error: missing script: build:clean;
4 verbose stack
4 verbose stack Did you mean one of these?
4 verbose stack     build:clean
4 verbose stack     build:watch

**Comment by hardyscc** [comment]
@benkburke @fishcharlie I didn't change the package.json on this PR. and seems that you are using windows, therefore the prepare script cannot be run properly.
```
    "prepare": "npm run build:clean; npm run build",
```
I just changed it as follow, in order to support mac, linux and windows.
```
    "prepare": "(npm run build:clean || true) && npm run build",
```
please retry again with `npm install hardyscc/dynamoose --save`

here is some reference :
https://medium.com/@chillypenguin/running-node-npm-scripts-sequentially-on-windows-8737dc24da1f

**Comment by benkburke** [comment]
@hardyscc The typings appear to be working now.  Thank you.

**Comment by sarjumulmi** [comment]
@hardyscc this still seems to be an issue even with 2.3.0. Was there another resolution to this? Thanks.

**Comment by hardyscc** [comment]
@sarjumulmi the corresponding PR moved to #983 and still not merge yet

**Comment by TranBaVinhSon** [comment]
I still get this error `2.3.0`, just couldn't query and scan

**Comment by hardyscc** [comment]
@TranBaVinhSon the #983 PR has ready been merged in master but still not release yet, however can install it using 
```
npm install dynamoose/dynamoose#master
```
